fix the concurrent pool.Close and client.Close
ProcessOut/grpc-go-pool pull request #5
Opened 2018-05-22 08:50 UTC by catlittlechen

```
package main

import (
	"context"
	"fmt"
	"time"

	grpcpool "github.com/processout/grpc-go-pool"
	"google.golang.org/grpc"
)

func f(p *grpcpool.Pool) {
	for {
		c, err := p.Get(context.Background())
		if err != nil {
			fmt.Printf("Get returned an error: %s\n", err.Error())
			return
		}
		c.Close()
	}
}

func main() {
	p, err := grpcpool.New(func() (*grpc.ClientConn, error) {
		return &grpc.ClientConn{}, nil
	}, 10, 10, 0)
	if err != nil {
		fmt.Printf("The pool returned an error: %s\n", err.Error())
		return
	}
	for i := 0; i < 10; i++ {
		go f(p)
	}
	time.Sleep(time.Second * 1)
	p.Close()
	select {}
}
```

This is my test code.
It will be panic because of the closed channel

2018-05-22 16:09 UTC, manuel-huez requested changes
Thanks a lot for your contribution!
From what I understand, your PR aims to handle the case in which the pool gets closed at the same time as a connection gets returned to the pool. Is there any additional change you made?

I've highlighted some comments I had about your changes, feel free to comment when it's an open question.
It'd also be great to have some tests covering your changes.

2018-05-22 16:09 UTC, manuel-huez commented on pool.go
> +		_ = client.ClientConn.Close()
You don't need to assign the result of `Close()` to `_`.

2018-05-22 16:09 UTC, manuel-huez commented on pool.go
> +	if p == nil {
I don't think this check is needed: a few lines below you use `p.IsClosed()` which already does this check.

2018-05-22 16:09 UTC, manuel-huez commented on pool.go
> +	case wrapper = <-p.clients:
We were using the `getClients` function to return a copy of the clients whilst making sure no concurrent access was made to it using the mutex. Your code is still safe from concurrent accesses, but the performances get worsened as the lock isn't freed until the function terminates. It'd be best to keep the previous logic where a copy is made to release the lock as soon as possible.

2018-05-22 16:09 UTC, manuel-huez commented on pool.go
> +		_ = wrapper.ClientConn.Close()
The assignation to `_` is not needed.

2018-05-22 16:09 UTC, manuel-huez commented on pool.go
> +			p.clients <- ClientConn{
As previously stated, it'd be best to use a copy of `p.clients` instead of relying a function-scoped lock, which doesn't free the lock as fast as we previously were doing.

2018-05-22 16:09 UTC, manuel-huez commented on pool.go
> +			return nil, err
I'm unsure why you added this line, as it doesn't change the behavior if the function. The `return` below was still correctly returning the generated error.

2018-05-22 16:09 UTC, manuel-huez commented on pool.go
> +		_ = c.ClientConn.Close()
Why did you change from `wrapper` to `c`? I don't have much time to wrap my head around the implications this change has, but it seems to be this changes the overall behavior of the code.
Also, please remove the assignation to `_`.

2018-05-22 16:09 UTC, manuel-huez commented on pool.go
> +	err := c.pool.put(c.ClientConn)
Why did you split the code to create this new `put` function? From what I can see it's only used once in the code.

2018-05-23 01:13 UTC, catlittlechen commented on pool.go
> +		_ = client.ClientConn.Close()
I use `gometalinter` to check my code. So I used _ to ignore the error. It's my habit....

2018-05-23 01:13 UTC, catlittlechen commented on pool.go
> +	if p == nil {
If p is nil, `p.mu.Lock()` will be panic. But after the code locked, IsClosed() will check whether it's closed or not...

2018-05-23 01:14 UTC, catlittlechen commented on pool.go
> +			return nil, err
Sorry. It's my habit..

2018-05-23 02:33 UTC, catlittlechen commented on pool.go
> +	case wrapper = <-p.clients:
I found `get_clients` has some Rlock logic. So I delete this function and use clients directly.

2018-05-23 02:38 UTC, catlittlechen commented on pool.go
> +	err := c.pool.put(c.ClientConn)
Of course this function is used once, but I this this logic should be a pool function. So I split the code to create this new one, and add some lock logic to project these.

2018-10-25 15:59 UTC, closed without merging