add-maxidle-test
ProcessOut/grpc-go-pool pull request #9
Opened 2018-07-22 06:28 UTC by dorkolog

@manuel-huez in addition to your [PR](https://github.com/processout/grpc-go-pool/pull/8), I've also added a similar test to idletimeout. 
Also, I reversed the if order (for some reason the current format confused me)

2018-07-26 16:27 UTC, manuel-huez commented on pool.go
> -	// If the wrapper connection has become too old, we want to recycle it. To
I'd rather keep this comment so future people can read this for reference. I'm not opposed to reversing the if logic, but if you do, please keep the comment & update it accordingly.

2018-07-26 16:28 UTC, manuel-huez requested changes
Please refer to my previous comment.

2018-07-30 07:35 UTC, dorkolog commented
@manuel-huez updated PR.

2018-08-01 14:09 UTC, manuel-huez approved these changes

2018-08-01 14:09 UTC, merged